CC=../gray386/bin/musl-gcc
CFLAGS:=-Wall -static -mno-red-zone -m32 -march=i386 -mtune=i386 -fno-stack-protector -fomit-frame-pointer -mno-mmx -mno-sse -fno-pic -std=c11 -ggdb3
.PHONY: all
all: xadd endbr32 bswap
